# Generated by Django 5.0.2 on 2024-02-22 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
