# Generated by Django 5.0.2 on 2024-02-22 14:08

import localflavor.us.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='zip_code',
            field=localflavor.us.models.USZipCodeField(blank=True, max_length=10),
        ),
    ]
