# Generated by Django 5.0.2 on 2024-02-22 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.location'),
        ),
    ]
